const nodemailer = require("nodemailer");
require("dotenv").config();

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: process.env.SMTP_PORT || 587,
  secure: process.env.SMTP_PORT == 465, // true for 465, false for other ports
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

exports.sendTeamCredentialsEmail = async (teamName, teamId, qrCodeDataUrl, recipients) => {
  if (!process.env.SMTP_HOST || !process.env.SMTP_USER) {
    console.warn("⚠ SMTP settings not configured. Skipping email sending.");
    return false;
  }

  try {
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333; line-height: 1.6;">
        <h2 style="color: #0f4c81;">Welcome to ${teamName}! 🎉</h2>
        <p>Your team has been successfully registered for the hackathon. Please save these credentials securely.</p>
        
        <div style="background-color: #f4f7f6; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <h3 style="margin-top: 0; color: #2c3e50;">Team ID: <strong><span style="font-size: 24px; color: #e74c3c;">${teamId}</span></strong></h3>
        </div>

        <h3>Authenticator Setup</h3>
        <p>We use Two-Factor Authentication (2FA) for secure login. To access your team dashboard, you must scan the QR code below using an Authenticator app (like Google Authenticator, Authy, or Microsoft Authenticator).</p>
        
        <ol>
          <li>Download <strong>Google Authenticator</strong> or <strong>Authy</strong> on your phone.</li>
          <li>Open the app and select <strong>Scan a QR Code</strong>.</li>
          <li>Scan the QR code attached below.</li>
          <li>When logging in, use the Team ID above and the 6-digit code generated by your app.</li>
        </ol>

        <div style="text-align: center; margin: 30px 0;">
          <img src="cid:qrcode" alt="Authenticator QR Code" style="width: 200px; height: 200px; border: 1px solid #ddd; border-radius: 12px; padding: 10px;"/>
        </div>

        <p>If you have any questions or issues, please reach out to the event organizers.</p>
        <p><em>Best regards,<br>The Organizing Team</em></p>
      </div>
    `;

    // Extract base64 data to attach it
    const base64Data = qrCodeDataUrl.split(',')[1];

    // Determine the array of emails
    // members could be an array of objects like [{ name: '..', email: '...', role: '...' }]
    const emailAddresses = recipients
      .map(member => member.email)
      .filter(email => email && email.trim() !== "");

    if (emailAddresses.length === 0) {
      console.warn(`⚠ No valid email addresses found for team: ${teamName}`);
      return false;
    }

    const info = await transporter.sendMail({
      from: process.env.SMTP_FROM || `"Hackathon Admin" <${process.env.SMTP_USER}>`,
      to: emailAddresses.join(', '),
      subject: `Your Team Credentials - ${teamName}`,
      html: htmlContent,
      attachments: [
        {
          filename: 'qrcode.png',
          content: base64Data,
          encoding: 'base64',
          cid: 'qrcode' // same cid value as in the html img src
        }
      ]
    });

    console.log(`✉ Email sent successfully to team ${teamName}: ${info.messageId}`);
    return true;
  } catch (error) {
    console.error("❌ Error sending team credentials email:", error);
    return false;
  }
};
